### PR TITLE
Added incrementor for Font size

### PR DESCRIPTION
**Pull request by Jcruz525**
I added some buttons to increment font size and made some refactoring changes. I hope this works let me know if i need to make changes.

### CODE REVIEW

**Review by chavi362 — CHANGES_REQUESTED** [review]
First of all, thank you so so much!!!
Th made the canks also for optimizing the code , the new function changeAllTextStyle made the code more readable and nice!
I have only one ask: please made the design nicer, maby put the + and - buttons on the same line, because now it doesn't look so nice the color became narrow and long and the font family became too much above.
Can you can please change this?
Thanks,
Best regards,
Cahvi

**Comment by Jcruz525** [comment]
Yes, I can do this!

**Comment by Jcruz525** [comment]
I also submitted a fix for the shift button error also. I am new to committing here so it seems it's in the same pull request for this issue also. Let me know if you see that.

**Comment by chavi362** [comment]
Yes I see, the review is about they bost. Can you please design it more?
Thank you so much!
Chavi

‫בתאריך יום ג׳, 2 בינו׳ 2024 ב-18:31 מאת ‪Johnny Cruz III‬‏ <‪
***@***.***‬‏>:‬

**Comment by Jcruz525** [comment]
Okay I changed the styling so that it is in-line with the font family section and the buttons are on either side of the font-size value. Let me know if you like this.

**Review by chavi362 — APPROVED** [review]
Exactly!!!
I see that you also solved the shift issue!!
I must tell you are really quick and genius!!!
I would be happy to see you more in virtual-keyboard!!!
Thank you so much!!!
Don't forget to star the repository and share it with your friends!
Best regards,
Chavi

**Pull request merged**
