### PR TITLE
Korean 2-set

### PR DESCRIPTION
**Pull request by N3v1**
This PR is about #13

### CODE REVIEW

**Review by chavi362 — CHANGES_REQUESTED** [review]
Please  add the suitable arr in keyboard.jsx
Good luck!

**Comment by chavi362** [comment]
@N3v1 are you still working on this?
If not, please close the PR

**Comment by N3v1** [comment]
@chavi362 Yes I'm still working on it - couldn't do it in the last weeks because I was busy with learning for my exams

**Comment by chavi362** [comment]
No problem, take your time.

‫בתאריך שבת, 20 בינו׳ 2024 ב-20:09 מאת ‪NH‬‏ ***@***.***‬‏>:‬

**Pull request closed without merging**
