### PR TITLE
Fixes #34

### LINKED ISSUE #34: When choosing emojis keyboard the button to regular keyboard become small and far

### PR DESCRIPTION
**Pull request by AtharvaMutsaddi**
### Issue #34 Resolved
Solved the issue: " When choosing emojis keyboard the button to regular keyboard become small and far #34 " . 
### Changes Made:
- Centered the Contents of the emoji button 
- Updated Size of keyboard Icon to be larger
- Aligned the Items to the center for more consistent spacing

### Before Changes
- [Emoji Button](https://drive.google.com/file/d/1gocbdNaKApWkTzDS51ZQ2vqsSEk6JEZU/view?usp=sharing)
- [Keyboard Icon](https://drive.google.com/file/d/17iDW7ir4EDODl0A5T0QJ2fRCEhJ8kN5W/view?usp=sharing)

### After Changes:
- [Emoji Button](https://drive.google.com/file/d/1FDkuV9T3a4RvUrJSeS4f2Y5FnHT3lmuY/view?usp=sharing)
- [Keyboard Icon](https://drive.google.com/file/d/112PWcOEWDwprYYxGV9hsA2kYZrp0mMxz/view?usp=sharing)

### CODE REVIEW

**Review by chavi362 — CHANGES_REQUESTED** [review]
Thank you so much!!!
It looks now so nice.!!!
I have only one remark: please remove the unnecessary code which you putted into comments so I can merge the code!
Please give the repository a star and share it with your friends
Thanks again
Chavi

**Comment by AtharvaMutsaddi** [comment]
Sure! Will do

**Comment by chavi362** [comment]
@AtharvaMutsaddi , I want so much to merge your PR!!!
Please solve the problem I tell you!

**Comment by AtharvaMutsaddi** [comment]
@chavi362 I have removed the commented code in my recent commit

**Pull request merged**
