### PR TITLE
Fixes #39

### LINKED ISSUE #39: Enhancement Suggestion: Implement Modals instead of alert popups for Improved User Experience
The current implementation relies heavily on alert popups for user interaction, which might disrupt the user flow and provide a less-than-optimal experience. To enhance the user experience and maintain a smooth workflow, I propose implementing modals in place of these alert popups.

### PR DESCRIPTION
**Pull request by AnviJamkhande**
Solved the issue: "Enhancement Suggestion: Implement Modals instead of alert popups for Improved User Experience https://github.com/chavi362/virtual-keyboard/issues/39"

### Changes made:
- Added a new modal on pressing copy icon using [reactjs-popup](https://www.npmjs.com/package/reactjs-popup?activeTab=readme)
- Changed previous alert text 
- Added styles and matching color to text and buttons

## Before changes:
- [Copy alert popup](https://drive.google.com/file/d/177hRD3Dmmoq_pIWADpGlYVZmYjiZaHf8/view?usp=drive_link)

## After:
- [Copy Modal](https://drive.google.com/file/d/13AzBaM8DPQhkx_w4SgN6gEqSFLn14xHE/view?usp=drive_link)

## Modified: 
- [Time based popup](https://drive.google.com/file/d/1m8StpJKM_mxk-8SUxbGOc8x4vH2wxSYP/view?usp=drive_link)

### CODE REVIEW

**Comment by AnviJamkhande** [comment]
hey! hope you are liking these changes. I have a couple more small suggestions, let me know if you would like to hear them out! Thanks!

**Review by chavi362 — COMMENTED** [review]
Thank you !!!
It's so nice now!!! The alert before was so ugly...
For a better user experience, I prefer that the user does not have to click on close, but it will disappear after about 2 seconds.
If you have the energy to do this, write to me, if not, write that you don't and I will merge it that way
I would be very happy if you have new ideas to improve the keyboard Please open issues about this and write me to assign you

**Comment by AnviJamkhande** [comment]
@chavi362 hey! i am so sorry for the late reply. Sure i would be glad to make that change! I will start working on it right away!

**Comment by AnviJamkhande** [comment]
i have added the modified screenshot in Fixes#39. let me know if you like the changes!

**Review by chavi362 — CHANGES_REQUESTED** [review]
@AnviJamkhande I'm sorry...
But doe to another PR I merged you have conflicts.
Can you please resolve them?

**Comment by AnviJamkhande** [comment]
@chavi362 done! let me know if you need something else

**Review by chavi362 — APPROVED** [review]
Wow!!
It's so nice!

**Pull request merged**
