### PR TITLE
useEmojiKeyBoard custom hook

### PR DESCRIPTION
**Pull request by tiago1820**
- -A custom hook was created that contains much of the content of the EmojiKeyBoard component.
- issue: #83

### CODE REVIEW

**Review by chavi362 — COMMENTED** [review]
Awesome!
It's really clean the code and make it cleared!
Note that the useEmojisKeyboard contain only array of emojis. So maybe we cancall it emojie array or emoji data for better understanding?

**Comment by tiago1820** [comment]
I'm glad you liked it.
I put this name to make it clear that this hook belongs to the EmojisKeyboard.
But if you want you can change the name as long as the word "use" remains at the beginning.

**Comment by chavi362** [comment]
Awesome, thank you so much!
can you do this?

**Comment by tiago1820** [comment]
Done.
useEmojiKeyBoard to useEmojiData.

**Pull request merged**
