### PR TITLE
code optimized and isUndo, isRedo done

### PR DESCRIPTION
**Pull request by kishoreravi24**
Hi @chavi362, take a look and try out in local and let me know if you want to change any!
Thanks,
Kishore

### CODE REVIEW

**Review by chavi362 — CHANGES_REQUESTED** [review]
Oops....
Your code isn't working...
See what happens in the console:StyleSelector.jsx:124  Uncaught ReferenceError: changeAllStyle is not defined
    at StyleSelector (StyleSelector.jsx:124:68)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)

**Comment by kishoreravi24** [comment]
@chavi362, please check now!
thanks

**Review by chavi362 — CHANGES_REQUESTED** [review]
first of all, thank you so much for your work!!! 
You still have one small issue: in style selector in this line: <button onClick={handleToggleChangeAllStyle} className={`${changeAllStyle ? 'active' : ''}`}>change all text's style</button>
you have to use instead of changeAllStyle changeAllStyleRef.current
Also, you till now use isUndo and isRedo, and you can sent the length of the stucks instead or find another solution for them.
(You can use stuck for all the operations and a array for the current text or something like that)

**Comment by chavi362** [comment]
@kishoreravi24 , how is your work?

**Comment by kishoreravi24** [comment]
Hi @chavi362 , please check all the commits , changeAllStyle changed to changeAllStyleRef.current !
then, regarding the isUndo and isRedo the current model is working fine and i think we can leave it, if you want to update it, please let me know, will do
Thanks
Kishore

**Comment by chavi362** [comment]
Thanks!!!
But due to #29 which was created and merged before yours one, there are conflicts.
Please resolve the conflicts so I can merge it.
Thank you so much!!!

**Comment by kishoreravi24** [comment]
Hi @chavi362 , done!

**Comment by chavi362** [comment]
@kishoreravi24 , note that now the option to chnage all text style doesn't work. Please repair it. Thank you!!!

**Pull request merged**
