### PR TITLE
Created select menu for Text-align

### PR DESCRIPTION
**Pull request by Jcruz525**
Hello @chavi362, I created a select menu for changing text-align. I know in your post you mentioned a sort of hamburger menu but I ran into some trouble with that. Let me know if this change works for you!

### CODE REVIEW

**Comment by Jcruz525** [comment]
Hey @chavi362, sorry there are so many changes I just wanted to add a few quick ones to this pull request I hope that works for you!

**Comment by chavi362** [comment]
Thank you for all of the changes!!! You don't have to feel sorry!
Once you finish, please tell me
Good Luck 🤞
Chavi

‫בתאריך שבת, 6 בינו׳ 2024 ב-22:20 מאת ‪Johnny Cruz III‬‏ <‪
***@***.***‬‏>:‬

**Comment by Jcruz525** [comment]
I think I am finished for now! Hope I helped out!

**Review by chavi362 — COMMENTED** [review]
First of all thank you so much!!
Note that your pr solves also #75 !!
And you also add the tooltip for download!!
Note that in real world like Microsoft Word, there is an option to change the align of only  now. So the change happens only when the user starts a new line and you simplicty change all the text also when the change all text style isn't active .
Can you please do this?
(you should also change the letterstyle class)
If you don't have energy to do that now, please tell me and I will merge it and we will work on this letter.
Best regards,
Chavi

**Comment by Jcruz525** [comment]
I can definitely do this another time if you assign the issue to me. I have been working for a while now so I probably will not get to it today. I can surely implement that soon. If the changes are good I would just merge them now and tomorrow I can get started on that change. :D

**Review by chavi362 — APPROVED** [review]
Thanks for everything!

**Pull request merged**
