### PR TITLE
Add functionality to 'tab' key for Issue #92

### LINKED ISSUE #92: Feat: tab button
Current now we have tab but it's not do anything

### PR DESCRIPTION
**Pull request by atilagulers**
Enable 4-space insertion on tab key press in virtual keyboard, resolves #92

### CODE REVIEW

**Review by chavi362 — COMMENTED** [review]
Hi @atilagulers ,
Your code is well structured and nice!
Can you please change to add "\t" instead of 4 spaces because it more clear?

**Comment by atilagulers** [comment]
Hi @chavi362 

at first i've done like that. But i thought it wasn't good for virtual keyboard :)

i'm on it.

**Review by chavi362 — CHANGES_REQUESTED** [review]
Note that now it's not working...

**Comment by atilagulers** [comment]
Yes, because /t does nothing on virtual keyboard. I've just changed "spaces" to "/t"

**Comment by chavi362** [comment]
Oh, so try using &#09
this is no breaking tab in js
If it's not work try 4 spaces


‫בתאריך יום ה׳, 25 בינו׳ 2024 ב-16:03 מאת ‪Atila Guler‬‏ <‪
***@***.***‬‏>:‬

**Comment by chavi362** [comment]
You cab also try &nbsp


‫בתאריך יום ה׳, 25 בינו׳ 2024 ב-16:24 מאת ‪Chavi developer‬‏ <‪
***@***.***‬‏>:‬

**Comment by atilagulers** [comment]
"&#9;" works.

by clicking tab I can navigate the buttons in order.

What do you think? is it okay?

**Comment by atilagulers** [comment]
&#9;

**Comment by atilagulers** [comment]
case
func


maybe something like this? we can navigate buttons right now by focusing

also if you want we can add all buttons, inputs, text areas etc..

if we select from document

**Comment by chavi362** [comment]
Do you know what? Let's do with 4 spaces as in the first time?
What do you think?

**Comment by atilagulers** [comment]
4 spaces is much better i guess. Because using real tab functionality on a virtual keyboard is a bit meaningless

**Comment by chavi362** [comment]
So can you reavt you last commit and submit the first pr?

**Review by chavi362 — APPROVED** [review]
Thank you so much!!!

**Pull request merged**
