### PR TITLE
fixed the #35 issue

### PR DESCRIPTION
**Pull request by Linnuxz**
I changed handleInputButtonClick function to make the functionality work as expected.

### CODE REVIEW

**Review by chavi362 — CHANGES_REQUESTED** [review]
First of all, thank you so much for your PR!!!
But note that you have one issue in the PR:  when clicking second time on change all style the change all style mode doesn't cancle!

**Comment by chavi362** [comment]
@Linnuxz I want so much to merge your PR!!!
Can you please repair this?

**Comment by chavi362** [comment]
@Linnuxz are you still working on this?

**Comment by Michalw101** [comment]
@Linnuxz I would like to work on this are you still working?

**Pull request closed without merging**
