### PR TITLE
Physical keyboard2

### PR DESCRIPTION
**Pull request by tiago1820**
Hello, @chavi362 

Added physical keyboard events to the letter and number keys and the "space" key.

The "enter", "backspace" and "caps lock" keys are missing.

To carry out the task I created a global state, for this I added Redux technology to the project. 
#7

### CODE REVIEW

**Review by chavi362 — CHANGES_REQUESTED** [review]
I must tell that your code is really nice and wise!!!
You are genius!
Note that when the language on the virtual keyboard is different from the language on the physical keyboard and the user types on the physical keyboard, it enters the language of the physical keyboard and I also want the typings on the physical keyboard to be in the language selected on the virtual keyboard.
Can you please fix it?

**Review by chavi362 — COMMENTED** [review]
Opssss... I'm sorry, I didn't recognize the issue well.
The problem is that the physical events work only for English. but for Arabic it doesn't work and if the virtual keyboard is on Hebrew state it writes in English

**Comment by chavi362** [comment]
Wow!!! I really appreciate your help and learning!
I would be glad if you can also manage this.
But if you don't able or don't have time you can now finish it without this
and after you will submit the PR about this and I or another contributor
will try to solve it.
Do whatever you want with this.

‫בתאריך יום ג׳, 12 בדצמ׳ 2023 ב-15:09 מאת ‪Tiago de Oliveira‬‏ <‪
***@***.***‬‏>:‬

**Comment by tiago1820** [comment]
I'm sorry, I'll check that out.
I'll fix the bugs, when everything is working fine I'll send another PR. :)

**Comment by chavi362** [comment]
Awesome, thank you so much! Y you don't have to be sorry!

‫בתאריך יום ג׳, 12 בדצמ׳ 2023 ב-19:44 מאת ‪Tiago de Oliveira‬‏ <‪
***@***.***‬‏>:‬

**Comment by chavi362** [comment]
@efratMIL , how is your work?

**Comment by tiago1820** [comment]
Hello, @chavi362 .

This week was complicated.
I am finishing a bootcamp project where I am studying:
[https://github.com/tiago1820/pokemon-pi
](url)
Tomorrow I will work on this topic again.

**Review by chavi362 — CHANGES_REQUESTED** [review]
Thanks!!!
Can you please remove the unnecessary code?
I mean the code that you putted into comments.
Thank you so much
Chavi

**Comment by tiago1820** [comment]
I'm sorry!
oops! I was wrong, I didn't have to do "push" yet.  I'm missing some things.  I thought the changes were only in my repository.

**Pull request merged**
