### PR TITLE
new feature - convert text to pdf

### PR DESCRIPTION
**Pull request by rachelifeld**
I added a feature that converts the text to a PDF file.

### CODE REVIEW

**Review by chavi362 — CHANGES_REQUESTED** [review]
Hi  @rachelifeld 
Firstly, I want to express my gratitude for your  pull request (#59) to add the "Convert to PDF" feature. Your contribution is highly appreciated! I must tell you that it is really good idea to add that feature.

I've noticed a conflict in your changes, and I kindly ask for your assistance in resolving it. 
Also, I want that the new button will be more designed: it should be with an icon of download (you can use react icon) or design in another way.
It won't should be in the bottom of the page but above next to the emojis button or in the side of the html file or you can consider another place.
If you have any questions please let me know!
Chavi

**Comment by rachelifeld** [comment]
Hi @chavi362,

Thank you for your feedback and guidance on the pull request (#59). I appreciate your positive remarks about the "Convert to PDF" feature.

I've addressed the conflict in my changes and redesigned the new button as per your suggestion. The button now features a download icon from React Icons and is positioned above next to the emojis button for better visibility.

If you have any further comments or if there's anything else you'd like me to modify, please let me know. I'm here to make sure the contribution aligns with the project's expectations.

Thank you again for your guidance!
Rachel

**Comment by chavi362** [comment]
Thank Rachel!!!
It's so nice now! I like the icon so much!
But you still have minor conflicts, can you please resolve them?
Thank you
Cahvi

‫בתאריך יום ה׳, 4 בינו׳ 2024 ב-14:37 מאת ‪rachelifeld‬‏ <‪
***@***.***‬‏>:‬

**Comment by rachelifeld** [comment]
Hi  @chavi362 ,


I've resolved the conflicts, and the changes should be good to go. If you have any further comments or if there's anything else you'd like me to check, please feel free to let me know.

Thanks
Rachel

**Review by chavi362 — APPROVED** [review]
Thank You, @rachelifeld! 🚀

Dear Rachel,

A huge thank you for your fantastic contribution! 🎉 Your addition of the "Convert to PDF" button is simply awesome and adds incredible value to the virtual keyboard. 🌈✨

Your dedication to enhancing the user experience and providing such a seamless conversion process is truly commendable. 🙌

Thank you for your hard work and creativity! 🚀 Looking forward to more incredible contributions from you in the future.

Best regards,
Chavi

**Comment by rachelifeld** [comment]
Hi @chavi362,

Thank you so much for your kind words and encouragement!  I'm delighted to hear that you found the "Convert to PDF" button valuable and that it enhances the virtual keyboard experience.

It's been a pleasure contributing to the project, and I'm thrilled to receive such positive feedback. Your support motivates me to continue striving for excellence in future contributions.

Looking forward to more collaboration and exciting additions to the project!

Best regards,
Rachel

**Pull request merged**
